// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGXluXPl90iTRy4gPEp6mxJ-Quh5hxQqg',
    appId: '1:328431110915:web:504267c2d1f168006e7736',
    messagingSenderId: '328431110915',
    projectId: 'protopharma-140d7',
    authDomain: 'protopharma-140d7.firebaseapp.com',
    storageBucket: 'protopharma-140d7.firebasestorage.app',
    measurementId: 'G-KLWKC81VQ6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk1qXo5Lg96G3vDOHvFfubcorsICE7nR0',
    appId: '1:328431110915:ios:5931c9ffde19a0b86e7736',
    messagingSenderId: '328431110915',
    projectId: 'protopharma-140d7',
    storageBucket: 'protopharma-140d7.firebasestorage.app',
    iosBundleId: 'com.example.protopharma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGXluXPl90iTRy4gPEp6mxJ-Quh5hxQqg',
    appId: '1:328431110915:web:8df7e0993113d5af6e7736',
    messagingSenderId: '328431110915',
    projectId: 'protopharma-140d7',
    authDomain: 'protopharma-140d7.firebaseapp.com',
    storageBucket: 'protopharma-140d7.firebasestorage.app',
    measurementId: 'G-D486TS1GR6',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk1qXo5Lg96G3vDOHvFfubcorsICE7nR0',
    appId: '1:328431110915:ios:5931c9ffde19a0b86e7736',
    messagingSenderId: '328431110915',
    projectId: 'protopharma-140d7',
    storageBucket: 'protopharma-140d7.firebasestorage.app',
    iosBundleId: 'com.example.protopharma',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1w8Ac-4F4nWS_fWEajyxdWgAjAOPyPRQ',
    appId: '1:328431110915:android:7e6758262ca1be966e7736',
    messagingSenderId: '328431110915',
    projectId: 'protopharma-140d7',
    storageBucket: 'protopharma-140d7.firebasestorage.app',
  );

}